export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADED = "USER_LOADED"
export const AUTH_FAIL = "AUTH_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const POST_ERROR = "POST_ERROR"
export const GET_POSTS = "GET_POSTS"
export const DELETE_POST = "DELETE_POST"
export const GET_POST = "GET_POST"
export const CREATE_POST = "CREATE_POST"
export const UPDATE_LIKE = "UPDATE_LIKE"

export const CREATE_COMMENT = "CREATE_COMMENT"
export const COMMENT_ERROR = "COMMENT_ERROR"
export const DELETE_COMMENT = "DELETE_COMMENT"
